spring.application.name=seatallocation

# Database Configuration using Environment Variables
spring.datasource.url=jdbc:mysql://localhost:3306/examdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true