spring.application.name=seatallocation

spring.datasource.url=jdbc:mysql://localhost:3306/examdb
spring.datasource.username=root
spring.datasource.password=exam1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true